name: 'ons_inequality'
version: '1.0.0'

profile: 'ons_inequality'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ons_inequality:
    stg_ons:
      +schema: stg_ons
      +materialized: view
      +tags: ["staging", "ons"]

      wellbeing:
        +tags: ["wellbeing"]

      income:
        +tags: ["income"]

    int_ons:
      +schema: int_ons
      +materialized: view
      +tags: ["intermediate", "ons"]

      wellbeing:
        +tags: ["wellbeing"]

      income:
        +tags: ["income"]

      time:
        +tags: ["time"]

      geography:
        +tags: ["geography"]

      data_quality:
        +tags: ["data_quality"]

    marts_ons:
      +schema: mart_ons
      +materialized: table
      +tags: ["mart", "ons"]

      core:
        wellbeing:
          +tags: ["wellbeing"]

        income:
          +tags: ["income"]

        time:
          +tags: ["time"]

        geography:
          +tags: ["geography"]

      reporting:
        +tags: ["reporting"]

seeds:
    ons_inequality:
        +schema: seed_ons
