

name: 'ons_inequality'
version: '1.0.0'

profile: 'ons_inequality'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ons_inequality:
    raw_ons:
      +schema: raw_ons
      +materialized: table
    stg_ons:
      +schema: stg_ons
      +materialized: view
    int_ons:
      +schema: int_ons
      +materialized: view
    marts_ons:
      +schema: mart_ons
      +materialized: table

seeds:
    ons_inequality:
        +schema: seed_ons